<?php

namespace App\Services;

class ComparisonDataService
{
    public static function getFestgeldOffers(): array
    {
        return [
            [
                'id' => 1,
                'bank_name' => 'Credit Europe Bank',
                'bank_logo' => '/images/banks/crediteurope.svg',
                'interest_rate' => 4.10,
                'max_rate' => 4.10,
                'term' => '12 Monate',
                'term_months' => 12,
                'guarantee' => 'Niederlande (100.000 €)',
                'min_deposit' => 1000,
                'max_deposit' => 100000,
                'rating' => 4.9,
                'reviews_count' => 1420,
                'featured' => true,
                'highlight' => 'Testsieger Höchstzins',
                'link' => '#angebot',
            ],
            [
                'id' => 2,
                'bank_name' => 'TF Bank',
                'bank_logo' => '/images/banks/tfbank.svg',
                'interest_rate' => 3.95,
                'max_rate' => 3.95,
                'term' => '12 Monate',
                'term_months' => 12,
                'guarantee' => 'Schweden (100.000 €)',
                'min_deposit' => 500,
                'max_deposit' => 100000,
                'rating' => 4.8,
                'reviews_count' => 980,
                'featured' => true,
                'highlight' => 'Top Bewertung',
                'link' => '#angebot',
            ],
            [
                'id' => 3,
                'bank_name' => 'Klarna Bank',
                'bank_logo' => '/images/banks/klarna.svg',
                'interest_rate' => 3.85,
                'max_rate' => 3.85,
                'term' => '12 Monate',
                'term_months' => 12,
                'guarantee' => 'Schweden (100.000 €)',
                'min_deposit' => 1,
                'max_deposit' => 500000,
                'rating' => 4.8,
                'reviews_count' => 3100,
                'featured' => false,
                'highlight' => 'Keine Mindestanlage',
                'link' => '#angebot',
            ],
            [
                'id' => 4,
                'bank_name' => 'SWK Bank',
                'bank_logo' => '/images/banks/swkbank.svg',
                'interest_rate' => 3.80,
                'max_rate' => 3.80,
                'term' => '24 Monate',
                'term_months' => 24,
                'guarantee' => 'Deutschland (100.000 €)',
                'min_deposit' => 2500,
                'max_deposit' => 100000,
                'rating' => 4.7,
                'reviews_count' => 640,
                'featured' => false,
                'highlight' => 'Deutscher Einlagenschutz',
                'link' => '#angebot',
            ],
            [
                'id' => 5,
                'bank_name' => 'Renault Bank direkt',
                'bank_logo' => '/images/banks/renaultbank.svg',
                'interest_rate' => 3.75,
                'max_rate' => 3.75,
                'term' => '12 Monate',
                'term_months' => 12,
                'guarantee' => 'Frankreich (100.000 €)',
                'min_deposit' => 2500,
                'max_deposit' => 250000,
                'rating' => 4.6,
                'reviews_count' => 870,
                'featured' => false,
                'highlight' => 'Beliebter Klassiker',
                'link' => '#angebot',
            ],
            [
                'id' => 6,
                'bank_name' => 'ING Deutschland',
                'bank_logo' => '/images/banks/ing.svg',
                'interest_rate' => 3.50,
                'max_rate' => 3.50,
                'term' => '12 Monate',
                'term_months' => 12,
                'guarantee' => 'Deutschland (100.000 €)',
                'min_deposit' => 1,
                'max_deposit' => 100000,
                'rating' => 4.9,
                'reviews_count' => 5400,
                'featured' => false,
                'highlight' => 'Beliebteste Direktbank',
                'link' => '#angebot',
            ],
        ];
    }

    public static function getTagesgeldOffers(): array
    {
        return [
            [
                'id' => 101,
                'bank_name' => 'TF Bank',
                'bank_logo' => '/images/banks/tfbank.svg',
                'interest_rate' => 3.60,
                'guarantee' => 'Schweden (100.000 €)',
                'bonus_term' => 'für 4 Monate garantiert',
                'min_deposit' => 0,
                'rating' => 4.8,
                'link' => '#tagesgeld',
            ],
            [
                'id' => 102,
                'bank_name' => 'Renault Bank direkt',
                'bank_logo' => '/images/banks/renaultbank.svg',
                'interest_rate' => 3.50,
                'guarantee' => 'Frankreich (100.000 €)',
                'bonus_term' => 'monatliche Zinsgutschrift',
                'min_deposit' => 0,
                'rating' => 4.7,
                'link' => '#tagesgeld',
            ],
            [
                'id' => 103,
                'bank_name' => 'ING Deutschland',
                'bank_logo' => '/images/banks/ing.svg',
                'interest_rate' => 3.30,
                'guarantee' => 'Deutschland (100.000 €)',
                'bonus_term' => 'Neukunden-Garantie 6 Mon.',
                'min_deposit' => 0,
                'rating' => 4.9,
                'link' => '#tagesgeld',
            ],
        ];
    }
}
